### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Bilalmesk** [aciurea/DragonCity-Bot#12]
when i run python scheduler.py  i get this  :
Traceback (most recent call last):
  File "C:\Users\bilal\OneDrive\Bureau\DragonCity-Bot-master\scheduler.py", line 1, in <module>
    from do_work import start_working
  File "C:\Users\bilal\OneDrive\Bureau\DragonCity-Bot-master\do_work.py", line 2, in <module>
    from alliance import Alliance
  File "C:\Users\bilal\OneDrive\Bureau\DragonCity-Bot-master\alliance.py", line 7, in <module>
    from popup import Popup
  File "C:\Users\bilal\OneDrive\Bureau\DragonCity-Bot-master\popup.py", line 9, in <module>
    jsonPos = get_json_file('popup.json')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilal\OneDrive\Bureau\DragonCity-Bot-master\utils.py", line 320, in get_json_file
    with open(f'positions/{resolution}/{file_name}') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'positions/1366x768/popup.json'

**Comment by Bilalmesk** [comment]
Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: 'positions/1366x768/popup.json'
  File "C:\Users\bilal\OneDrive\Bureau\DragonCity-Bot-master\utils.py", line 320, in get_json_file
    with open(f'positions/{resolution}/{file_name}') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilal\OneDrive\Bureau\DragonCity-Bot-master\popup.py", line 9, in <module>
    jsonPos = get_json_file('popup.json')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bilal\OneDrive\Bureau\DragonCity-Bot-master\alliance.py", line 7, in <module>
    from popup import Popup
  File "C:\Users\bilal\OneDrive\Bureau\DragonCity-Bot-master\do_work.py", line 2, in <module>
    from alliance import Alliance
  File "C:\Users\bilal\OneDrive\Bureau\DragonCity-Bot-master\scheduler.py", line 1, in <module>
    from do_work import start_working
FileNotFoundError: [Errno 2] No such file or directory: 'positions/1366x768/popup.json'

**Comment by aciurea** [comment]
Hey,
The problem is that `positions/1366x768/popup.json` this file doesn't
exist. You have a different resolution than I have.

It will be updated to not use the resolution like this, but I don't have
time, and you have to have the same screenshots as me in order for the
program to work.

Cheers,

Alin

**Comment by Bilalmesk** [comment]
So can i create my own file with my resolution

**Comment by aciurea** [comment]
Yes, you can do that.

There is one thing, the scripts are optimized for my map. Yours will be
100% different, multiple changes might be required.

In the future, there will be no resolution screen, I am migrating to a
different pattern, but I don't have much time to work on it.

Cheers

**Comment by Bilalmesk** [comment]
Thank for help
